title: Sergio Iglesias García

logo: ./img/imagen_temporal.png

description: Desarrollador de aplicaciones web

theme: jekyll-theme-hacker

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: sergiotur04@gmail.com







